// Copyright 2025 Jascha Wanger / Tarnover, LLC
// SPDX-License-Identifier: Apache-2.0
//
// Cross-language compatibility tests.
//
// Loads the JSON fixtures generated by `scripts/generate_test_vectors.py`
// and asserts that this TypeScript port produces byte-for-byte
// identical canonical bytes, hashes, and signatures. If the Python,
// Rust, and TS implementations disagree, these tests catch it before
// any pin signed by one is rejected by another.

import { describe, it } from 'node:test';
import { strict as assert } from 'node:assert';
import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

import {
  b64UrlDecodeNoPad,
  b64UrlEncodeNoPad,
  canonicalizeHeader,
  pinFromJSON,
  pinToJSON,
} from '../src/attestation.js';
import { hashText, hashVector, type VecDtype } from '../src/hash.js';
import { Signer } from '../src/signer.js';
import { Verifier, VerifyErrorCode } from '../src/verifier.js';

const HERE = dirname(fileURLToPath(import.meta.url));
const TESTVECTORS_DIR = join(HERE, '..', '..', 'testvectors');

interface V2Bundle {
  version: number;
  domain_tag_b64: string;
  public_key_b64: string;
  private_key_b64: string;
  key_id: string;
  fixtures: V2Fixture[];
}

interface V2Fixture {
  name: string;
  description: string;
  input: {
    source: string;
    model: string;
    vec_b64: string;
    vec_dtype: VecDtype;
    vec_dim: number;
    timestamp: string;
    model_hash?: string;
    extra?: Record<string, string>;
  };
  pin_json: string;
  expected_canonical_bytes_b64: string;
  expected_vec_hash: string;
  expected_source_hash: string;
}

interface V2NegativeBundle {
  version: number;
  public_key_b64: string;
  private_key_b64: string;
  key_id: string;
  fixtures: V2NegativeFixture[];
}

interface V2NegativeFixture {
  name: string;
  description: string;
  expected_failure: string;
  pin_json: string;
  tampered_vec_b64?: string;
  tampered_source?: string;
  original_source?: string;
  vec_dtype?: VecDtype;
  vec_dim?: number;
  nan_vec_b64?: string;
  expected_model?: string;
  expected_record_id?: string;
}

function loadV2(): V2Bundle {
  return JSON.parse(readFileSync(join(TESTVECTORS_DIR, 'v2.json'), 'utf8')) as V2Bundle;
}

function loadV2Negative(): V2NegativeBundle {
  return JSON.parse(
    readFileSync(join(TESTVECTORS_DIR, 'negative_v2.json'), 'utf8'),
  ) as V2NegativeBundle;
}

function parseVecF32(bytes: Uint8Array, dim: number): Float32Array {
  assert.equal(bytes.length, dim * 4, 'f32 fixture length sanity check');
  const out = new Float32Array(dim);
  const view = new DataView(bytes.buffer, bytes.byteOffset, bytes.byteLength);
  for (let i = 0; i < dim; i++) {
    out[i] = view.getFloat32(i * 4, /* littleEndian */ true);
  }
  return out;
}

function parseVecF64(bytes: Uint8Array, dim: number): Float64Array {
  assert.equal(bytes.length, dim * 8, 'f64 fixture length sanity check');
  const out = new Float64Array(dim);
  const view = new DataView(bytes.buffer, bytes.byteOffset, bytes.byteLength);
  for (let i = 0; i < dim; i++) {
    out[i] = view.getFloat64(i * 8, /* littleEndian */ true);
  }
  return out;
}

describe('cross-language v2 positive fixtures (testvectors/v2.json)', () => {
  const bundle = loadV2();
  assert.equal(bundle.version, 2, 'fixture file declares v2');
  assert.ok(bundle.fixtures.length > 0, 'no fixtures to test');

  for (const fx of bundle.fixtures) {
    it(`fixture: ${fx.name}`, async () => {
      const dtype = fx.input.vec_dtype;
      const rawBytes = b64UrlDecodeNoPad(fx.input.vec_b64);
      const vector =
        dtype === 'f32'
          ? parseVecF32(rawBytes, fx.input.vec_dim)
          : parseVecF64(rawBytes, fx.input.vec_dim);

      // 1. Component hashes line up with what Python recorded.
      assert.equal(hashText(fx.input.source), fx.expected_source_hash, 'source_hash');
      assert.equal(hashVector(vector, dtype), fx.expected_vec_hash, 'vec_hash');

      // 2. Reproduce the pin from the deterministic seed and confirm
      //    the canonical bytes + signed JSON match Python's output
      //    byte-for-byte (Ed25519 is deterministic).
      const seed = b64UrlDecodeNoPad(bundle.private_key_b64);
      const signer = Signer.fromPrivateBytes(seed, bundle.key_id);
      const pubExpected = b64UrlDecodeNoPad(bundle.public_key_b64);
      assert.deepEqual(
        Array.from(await signer.publicKeyBytes()),
        Array.from(pubExpected),
        'public key derivation',
      );

      const pin = await signer.pin({
        source: fx.input.source,
        model: fx.input.model,
        vector,
        vecDtype: dtype,
        timestamp: fx.input.timestamp,
        modelHash: fx.input.model_hash,
        extra: fx.input.extra,
      });

      const canonicalActual = canonicalizeHeader(pin.header);
      const canonicalExpected = b64UrlDecodeNoPad(fx.expected_canonical_bytes_b64);
      assert.equal(
        b64UrlEncodeNoPad(canonicalActual),
        b64UrlEncodeNoPad(canonicalExpected),
        'canonical bytes byte-for-byte',
      );

      const producedJson = pinToJSON(pin);
      assert.equal(producedJson, fx.pin_json, 'pin JSON byte-for-byte');

      // 3. Round-trip through pinFromJSON; verify the parsed pin.
      const parsed = pinFromJSON(producedJson);
      const verifier = new Verifier({ [bundle.key_id]: pubExpected });
      const r1 = await verifier.verify(parsed, { source: fx.input.source });
      assert.equal(r1.ok, true, `parsed pin verify: ${r1.error} ${r1.detail}`);

      // 4. Verify the JSON Python emitted directly.
      const pythonPin = pinFromJSON(fx.pin_json);
      const r2 = await verifier.verify(pythonPin, { source: fx.input.source });
      assert.equal(r2.ok, true, `python pin verify: ${r2.error} ${r2.detail}`);
    });
  }
});

describe('cross-language v2 negative fixtures (testvectors/negative_v2.json)', () => {
  const bundle = loadV2Negative();
  const pubKey = b64UrlDecodeNoPad(bundle.public_key_b64);

  for (const fx of bundle.fixtures) {
    it(`negative fixture: ${fx.name}`, async () => {
      const expected = fx.expected_failure.toLowerCase();

      // Many negative fixtures fail at parse time. We unify parse
      // failures with verify failures by distinguishing the
      // "version mismatch" subset (UNSUPPORTED_VERSION) from other
      // structural failures (PARSE_ERROR). The spec leaves that
      // boundary up to the implementation.
      let pin: ReturnType<typeof pinFromJSON> | undefined;
      let parseErr: string | undefined;
      try {
        pin = pinFromJSON(fx.pin_json);
      } catch (e) {
        parseErr = e instanceof Error ? e.message : String(e);
      }

      if (parseErr !== undefined) {
        const actual = /version/i.test(parseErr)
          ? VerifyErrorCode.UNSUPPORTED_VERSION
          : VerifyErrorCode.PARSE_ERROR;
        assert.equal(
          actual,
          expected,
          `${fx.name}: parser rejected with ${actual} but fixture expected ${expected} (msg: ${parseErr})`,
        );
        return;
      }

      const verifier = new Verifier({ [bundle.key_id]: pubKey });

      // Build verify options from optional fixture fields.
      const opts: Parameters<Verifier['verify']>[1] = {};
      if (fx.tampered_source !== undefined) {
        opts.source = fx.tampered_source;
      }
      if (fx.expected_model !== undefined) {
        opts.expectedModel = fx.expected_model;
      }
      if (fx.expected_record_id !== undefined) {
        opts.expectedRecordId = fx.expected_record_id;
      }
      if (fx.tampered_vec_b64 !== undefined && fx.vec_dtype && fx.vec_dim !== undefined) {
        const bytes = b64UrlDecodeNoPad(fx.tampered_vec_b64);
        opts.vector =
          fx.vec_dtype === 'f32' ? parseVecF32(bytes, fx.vec_dim) : parseVecF64(bytes, fx.vec_dim);
      }
      if (fx.nan_vec_b64 !== undefined && fx.vec_dtype && fx.vec_dim !== undefined) {
        const bytes = b64UrlDecodeNoPad(fx.nan_vec_b64);
        opts.vector =
          fx.vec_dtype === 'f32' ? parseVecF32(bytes, fx.vec_dim) : parseVecF64(bytes, fx.vec_dim);
      }

      const result = await verifier.verify(pin!, opts);
      assert.equal(result.ok, false, `${fx.name}: expected failure but got OK`);
      assert.equal(
        result.error,
        expected,
        `${fx.name}: expected ${expected} but got ${result.error} (${result.detail})`,
      );
    });
  }

  it('codespace coverage: all expected_failure codes map to a VerifyErrorCode', () => {
    const codes = new Set(Object.values(VerifyErrorCode));
    for (const fx of bundle.fixtures) {
      const expected = fx.expected_failure.toLowerCase();
      assert.ok(
        codes.has(expected as VerifyErrorCode),
        `${fx.name}: expected_failure ${fx.expected_failure} (${expected}) is not a VerifyErrorCode`,
      );
    }
  });
});

describe('strict v2 verifier rejects v1 fixtures', () => {
  // Strict v2 verifier should refuse every pin in v1.json as
  // UNSUPPORTED_VERSION (parser may also fail earlier, which is fine).
  interface V1Bundle {
    public_key_b64: string;
    key_id: string;
    fixtures: { name: string; expected: { pin_json: string } }[];
  }
  const v1 = JSON.parse(readFileSync(join(TESTVECTORS_DIR, 'v1.json'), 'utf8')) as V1Bundle;
  const pubKey = b64UrlDecodeNoPad(v1.public_key_b64);
  const verifier = new Verifier({ [v1.key_id]: pubKey });

  for (const fx of v1.fixtures) {
    it(`rejects v1 fixture ${fx.name}`, async () => {
      // Either the parser refuses the v=1 pin, or the verifier
      // returns UNSUPPORTED_VERSION. Both are acceptable; we just
      // assert it is NOT accepted.
      let parsed: ReturnType<typeof pinFromJSON> | undefined;
      let threw = false;
      try {
        parsed = pinFromJSON(fx.expected.pin_json);
      } catch {
        threw = true;
      }
      if (threw) {
        return; // strict parser refused — that's the contract.
      }
      const r = await verifier.verify(parsed!);
      assert.equal(r.ok, false, 'v1 pin must not verify under strict v2');
      assert.equal(r.error, VerifyErrorCode.UNSUPPORTED_VERSION);
    });
  }
});
