// Copyright 2025 Jascha Wanger / Tarnover, LLC
// SPDX-License-Identifier: Apache-2.0

//! Cross-language compatibility tests for protocol v2.
//!
//! Loads `testvectors/v2.json` (positive fixtures) and
//! `testvectors/negative_v2.json` (negative fixtures) generated by the
//! Python reference. Asserts:
//!
//! - Rust produces byte-for-byte identical canonical bytes for every
//!   positive fixture (`expected_canonical_bytes_b64`).
//! - Rust produces byte-for-byte identical pin JSON (Ed25519 is
//!   deterministic, so the signature must also match).
//! - Rust verifies every Python-produced pin under the same key.
//! - Each negative fixture maps to the expected `VerifyError` variant.

use std::path::PathBuf;

use base64::Engine;
use serde::Deserialize;
use serde_json::Value;

use vectorpin::{
    hash::{hash_text, hash_vector, VecDtype, VectorRef},
    KeyEntry, Pin, Signer, Verifier, VerifyError, VerifyOptions,
};

// ---- v2 positive fixtures ----------------------------------------------

#[derive(Debug, Deserialize)]
struct V2Bundle {
    public_key_b64: String,
    private_key_b64: String,
    key_id: String,
    fixtures: Vec<V2Fixture>,
}

#[derive(Debug, Deserialize)]
struct V2Fixture {
    name: String,
    input: V2Input,
    pin_json: String,
    expected_canonical_bytes_b64: String,
    expected_vec_hash: String,
    expected_source_hash: String,
}

#[derive(Debug, Deserialize)]
struct V2Input {
    source: String,
    model: String,
    vec_b64: String,
    vec_dtype: String,
    vec_dim: usize,
    timestamp: String,
    #[serde(default)]
    model_hash: Option<String>,
    #[serde(default)]
    extra: std::collections::BTreeMap<String, String>,
}

fn b64(s: &str) -> Vec<u8> {
    base64::engine::general_purpose::URL_SAFE_NO_PAD
        .decode(s.as_bytes())
        .expect("base64 fixture input")
}

fn testvectors_dir() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("..")
        .join("..")
        .join("testvectors")
}

fn parse_vec_f32(bytes: &[u8], dim: usize) -> Vec<f32> {
    assert_eq!(bytes.len(), dim * 4, "f32 fixture length sanity check");
    bytes
        .chunks_exact(4)
        .map(|c| f32::from_le_bytes(c.try_into().unwrap()))
        .collect()
}

fn parse_vec_f64(bytes: &[u8], dim: usize) -> Vec<f64> {
    assert_eq!(bytes.len(), dim * 8, "f64 fixture length sanity check");
    bytes
        .chunks_exact(8)
        .map(|c| f64::from_le_bytes(c.try_into().unwrap()))
        .collect()
}

fn run_v2_fixture(bundle: &V2Bundle, fx: &V2Fixture) {
    eprintln!("running v2 fixture: {}", fx.name);
    let dtype = VecDtype::parse(&fx.input.vec_dtype).expect("known dtype");
    let raw_bytes = b64(&fx.input.vec_b64);

    // 1. Hash equality on text and vector.
    assert_eq!(
        hash_text(&fx.input.source),
        fx.expected_source_hash,
        "source_hash mismatch for {}",
        fx.name
    );
    let computed_vec_hash = match dtype {
        VecDtype::F32 => {
            let v = parse_vec_f32(&raw_bytes, fx.input.vec_dim);
            hash_vector(VectorRef::F32(&v), dtype)
        }
        VecDtype::F64 => {
            let v = parse_vec_f64(&raw_bytes, fx.input.vec_dim);
            hash_vector(VectorRef::F64(&v), dtype)
        }
    };
    assert_eq!(
        computed_vec_hash, fx.expected_vec_hash,
        "vec_hash mismatch for {}",
        fx.name
    );

    // 2. Reproduce the pin from the deterministic seed.
    let signer = Signer::from_private_bytes(&b64(&bundle.private_key_b64), bundle.key_id.clone())
        .expect("seed loads");
    assert_eq!(
        signer.public_key_bytes().to_vec(),
        b64(&bundle.public_key_b64),
        "public key disagreement"
    );

    let opts = vectorpin::signer::PinOptions {
        dtype: Some(dtype),
        timestamp: Some(fx.input.timestamp.clone()),
        model_hash: fx.input.model_hash.clone(),
        extra: fx.input.extra.clone(),
    };
    let pin = match dtype {
        VecDtype::F32 => {
            let v = parse_vec_f32(&raw_bytes, fx.input.vec_dim);
            signer
                .pin_with_options(&fx.input.source, &fx.input.model, v.as_slice(), opts)
                .unwrap()
        }
        VecDtype::F64 => {
            let v = parse_vec_f64(&raw_bytes, fx.input.vec_dim);
            signer
                .pin_with_options(&fx.input.source, &fx.input.model, v.as_slice(), opts)
                .unwrap()
        }
    };

    // Canonical bytes must match Python output (domain tag + JSON body).
    let canonical = pin.header.canonicalize();
    let expected_canonical = b64(&fx.expected_canonical_bytes_b64);
    assert_eq!(
        canonical, expected_canonical,
        "canonical header bytes mismatch for {}",
        fx.name
    );

    // Pin JSON must match exactly — Ed25519 is deterministic.
    assert_eq!(
        pin.to_json(),
        fx.pin_json,
        "pin JSON mismatch for {}",
        fx.name
    );

    // Round-trip and verify.
    let parsed = Pin::from_json(&pin.to_json()).expect("rust parses its own JSON");
    let mut verifier = Verifier::new();
    verifier
        .add_key(&bundle.key_id, signer.public_key_bytes())
        .unwrap();
    verifier
        .verify_full::<&[f32]>(&parsed, Some(&fx.input.source), None, None)
        .expect("rust verifies own pin");

    // Also verify the Python-produced JSON directly.
    let python_pin = Pin::from_json(&fx.pin_json).expect("rust parses python JSON");
    verifier
        .verify_full::<&[f32]>(&python_pin, Some(&fx.input.source), None, None)
        .expect("rust verifies python-produced pin");
}

#[test]
fn cross_language_v2_positive_fixtures() {
    let path = testvectors_dir().join("v2.json");
    let raw = std::fs::read_to_string(&path).expect("read v2.json");
    let bundle: V2Bundle = serde_json::from_str(&raw).expect("parse v2.json");
    assert!(!bundle.fixtures.is_empty(), "no v2 fixtures to test");
    for fx in &bundle.fixtures {
        run_v2_fixture(&bundle, fx);
    }
}

// ---- v2 negative fixtures ----------------------------------------------

#[derive(Debug, Deserialize)]
struct V2NegativeBundle {
    public_key_b64: String,
    key_id: String,
    fixtures: Vec<V2NegativeFixture>,
}

#[derive(Debug, Deserialize)]
struct V2NegativeFixture {
    name: String,
    expected_failure: String,
    pin_json: String,
    #[serde(default)]
    tampered_vec_b64: Option<String>,
    #[serde(default)]
    nan_vec_b64: Option<String>,
    #[serde(default)]
    #[allow(dead_code)]
    vec_dtype: Option<String>,
    #[serde(default)]
    vec_dim: Option<usize>,
    #[serde(default)]
    tampered_source: Option<String>,
    #[serde(default)]
    expected_model: Option<String>,
    #[serde(default)]
    expected_record_id: Option<String>,
}

fn classify(err: &VerifyError) -> &'static str {
    match err {
        VerifyError::UnsupportedVersion(_) => "UNSUPPORTED_VERSION",
        VerifyError::UnknownKey(_) => "UNKNOWN_KEY",
        VerifyError::KeyExpired => "KEY_EXPIRED",
        VerifyError::ParseError(_) => "PARSE_ERROR",
        VerifyError::SignatureInvalid => "SIGNATURE_INVALID",
        VerifyError::VectorTampered => "VECTOR_TAMPERED",
        VerifyError::SourceMismatch => "SOURCE_MISMATCH",
        VerifyError::ModelMismatch { .. } => "MODEL_MISMATCH",
        VerifyError::ShapeMismatch { .. } => "SHAPE_MISMATCH",
        VerifyError::RecordMismatch => "RECORD_MISMATCH",
        VerifyError::CollectionMismatch => "COLLECTION_MISMATCH",
        VerifyError::TenantMismatch => "TENANT_MISMATCH",
        VerifyError::UnsupportedDtype(_) => "PARSE_ERROR",
        VerifyError::KeyDecodeFailed(_) => "UNKNOWN_KEY",
    }
}

fn run_negative(bundle: &V2NegativeBundle, fx: &V2NegativeFixture) {
    eprintln!(
        "running negative_v2 fixture: {} ({})",
        fx.name, fx.expected_failure
    );
    let mut verifier = Verifier::new();
    let pk: [u8; 32] = b64(&bundle.public_key_b64)
        .try_into()
        .expect("public key 32 bytes");
    verifier.add_key(&bundle.key_id, pk).unwrap();

    // The pin may fail to parse — that itself is a PARSE_ERROR outcome.
    let parsed = match Pin::from_json(&fx.pin_json) {
        Ok(p) => p,
        Err(e) => {
            let mapped: VerifyError = e.into();
            assert_eq!(
                classify(&mapped),
                fx.expected_failure,
                "{}: parse error class mismatch (got {mapped:?})",
                fx.name
            );
            return;
        }
    };

    let dtype = parsed.header.vec_dtype.clone();
    let vec_holder_f32: Vec<f32>;
    let vec_holder_f64: Vec<f64>;
    let vec_ref: Option<VectorRef<'_>> = if let Some(b) = &fx.tampered_vec_b64 {
        match dtype.as_str() {
            "f32" => {
                vec_holder_f32 = parse_vec_f32(&b64(b), fx.vec_dim.unwrap());
                Some(VectorRef::F32(&vec_holder_f32))
            }
            "f64" => {
                vec_holder_f64 = parse_vec_f64(&b64(b), fx.vec_dim.unwrap());
                Some(VectorRef::F64(&vec_holder_f64))
            }
            _ => panic!("unknown dtype {dtype}"),
        }
    } else if let Some(b) = &fx.nan_vec_b64 {
        // NaN-bearing vector — used for the nan_in_vector_at_verify case.
        match dtype.as_str() {
            "f32" => {
                vec_holder_f32 = parse_vec_f32(&b64(b), fx.vec_dim.unwrap());
                Some(VectorRef::F32(&vec_holder_f32))
            }
            "f64" => {
                vec_holder_f64 = parse_vec_f64(&b64(b), fx.vec_dim.unwrap());
                Some(VectorRef::F64(&vec_holder_f64))
            }
            _ => panic!("unknown dtype {dtype}"),
        }
    } else {
        None
    };

    let opts = VerifyOptions {
        source: fx.tampered_source.as_deref(),
        vector: vec_ref,
        expected_model: fx.expected_model.as_deref(),
        expected_record_id: fx.expected_record_id.as_deref(),
        ..VerifyOptions::default()
    };
    let err = verifier
        .verify(&parsed, opts)
        .expect_err("negative fixture must fail");
    assert_eq!(
        classify(&err),
        fx.expected_failure,
        "{}: error class mismatch (got {err:?})",
        fx.name
    );
}

#[test]
fn cross_language_v2_negative_fixtures() {
    let path = testvectors_dir().join("negative_v2.json");
    let raw = std::fs::read_to_string(&path).expect("read negative_v2.json");

    // Some negative fixtures intentionally exceed the JSON size cap, so
    // the bundle is large; parse it as Value first then pick out the
    // fields we need.
    let val: Value = serde_json::from_str(&raw).expect("parse negative_v2.json root");
    let bundle = V2NegativeBundle {
        public_key_b64: val["public_key_b64"].as_str().unwrap().to_string(),
        key_id: val["key_id"].as_str().unwrap().to_string(),
        fixtures: serde_json::from_value(val["fixtures"].clone()).expect("parse negative fixtures"),
    };

    assert!(!bundle.fixtures.is_empty());
    for fx in &bundle.fixtures {
        run_negative(&bundle, fx);
    }
}

// ---- v1 legacy verifier (migration path) -------------------------------

#[derive(Debug, Deserialize)]
struct V1Bundle {
    public_key_b64: String,
    key_id: String,
    fixtures: Vec<V1Fixture>,
}

#[derive(Debug, Deserialize)]
struct V1Fixture {
    name: String,
    expected: V1Expected,
}

#[derive(Debug, Deserialize)]
struct V1Expected {
    pin_json: String,
}

#[test]
fn legacy_v1_verifier_accepts_all_v1_fixtures() {
    let path = testvectors_dir().join("v1.json");
    let raw = std::fs::read_to_string(&path).expect("read v1.json");
    let bundle: V1Bundle = serde_json::from_str(&raw).expect("parse v1.json");

    let pk: [u8; 32] = b64(&bundle.public_key_b64).try_into().expect("32 bytes");
    let mut verifier = vectorpin::LegacyV1Verifier::new();
    verifier.add_key_entry(
        &bundle.key_id,
        KeyEntry::from_public_bytes(pk).expect("valid key"),
    );

    for fx in &bundle.fixtures {
        eprintln!("legacy v1 fixture: {}", fx.name);
        let pin =
            vectorpin::LegacyV1Verifier::parse_pin(&fx.expected.pin_json).expect("parse v1 pin");
        verifier
            .verify(&pin, VerifyOptions::default())
            .expect("legacy verifier accepts v1");
    }
}
